platform :ios, '8.0'
  targetsArray = ['GeneralArchitecture', 'GeneralArchitectureDev']

  # 循环
  targetsArray.each do |t|
      target t do
          pod 'MBProgressHUD', '~> 0.9.2'
          pod 'JSONModel'
          pod 'SDWebImage', '~>3.7'
          pod 'MJRefresh'
          pod 'AFNetworking', '~> 3.0.4'
          pod 'AvoidCrash'
          pod 'Masonry', '~> 1.0.0'
          pod 'DZNEmptyDataSet'
          pod 'UITableView+FDTemplateLayoutCell'
      end
end
